### ISSUE TITLE
catalogs stripped from manifest

### ISSUE THREAD

**Issue by arubdesu** [hjuutilainen/munkiadmin#82] opened 2015-08-07 13:36 UTC
Noticed on two so far, after making changes(and I believe I tried to fix by using contextual menu to add catalogs) catalog array gets changed to `<array/>`

**Comment by hjuutilainen** [comment] 2015-08-07 13:49
Are you using 1.2.1?

**Comment by arubdesu** [comment] 2015-08-07 13:49
yessir

**Comment by hjuutilainen** [comment] 2015-08-07 14:08
Can you reproduce it? If not, what were you doing before they disappeared? Anything in MunkiAdmin logs?

**Comment by arubdesu** [comment] 2015-08-07 16:07
None of my manifests have showed catalogs in the list view since 1.2 AFAIK, but it doesn't wipe the catalog array until I make a modification in the GUI and click save. I have very verbose logs and a screencast

**Comment by hjuutilainen** [comment] 2015-08-07 16:32
Do you have the catalogs folder in your repo or do you run makecatalogs on server? If there's no catalogs visible in the manifests view to begin with, there might be a bug reading them only from manifests. 

MunkiAdmin detects which files you have edited and only tries to write those back to disk. If it just wrote everything blindly you'd probably have zero catalogs right now...

**Comment by arubdesu** [comment] 2015-08-07 16:34
the iMac of the staging server I'm running MunkiAdmin on has a catalogs folder, nothing complex or fancy

**Comment by hjuutilainen** [comment] 2015-08-07 17:33
Could you send me those logs and screencast? I'm having a hard time trying to reproduce this. Feel free to upload the repository too if you can and feel like it's going to help (pkgsinfo and manifests or manifests only).

Here's a file request page to upload straight to my Dropbox:
https://www.dropbox.com/request/FIkdpgLwOjfB6Fk33z6J?oref=e

**Comment by erikng** [comment] 2015-08-07 17:37
I think there is a bigger issue here. Comparing a manifest xml vs what MunkiAdmin sees.

It does not appear that it is properly processing catalogs at all. According to MA, there are no catalogs set, but there are.

**Comment by arubdesu** [comment] 2015-08-07 20:12
Uploaded, pardon I didn't shape it down to highlight relevant parts. Please let me know if Dropbox didn't actually get it to you

**Comment by hjuutilainen** [comment] 2015-08-08 09:33
Thanks for the files. Judging by the log and the screencast, the manifest analyzing phase doesn't complete successfully. This causes all sorts of problems where and is usually caused by a broken manifest. I can actually reproduce this bug (and all sorts of other weirdness) by adding the following manifest in my fully functional repo and opening with v1.2.1:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>catalogs</key>
        <array>
            <string>production</string>
        </array>
        <key>included_manifests</key>
        <array>
            <string>this-manifest-does-not-exist!!</string>
        </array>
    </dict>
    </plist>

Most of the issues related to this have been resolved in 939b188 but could you test with a custom build:
https://dl.dropboxusercontent.com/u/7637076/MunkiAdmin-1.2.1-3-g939b188.dmg

If MunkiAdmin detects broken references in manifest it logs a message:
```Error: Could not link included_manifest object 4 --> Name: this-manifest-does-not-exist!!```

**Comment by erikng** [comment] 2015-08-10 12:10
In my testing, this custom build fixed all of my machine manifests.

Looking at the logs, this was indeed my issue as well. One of our locations had a manifest that is not referenced correctly.

**Comment by 48kRAM** [comment] 2015-08-10 13:13
I can add that I'm seeing this exact issue on 1.2.1 as well. The manifest edit mode wasn't showing my catalogs and saving the manifest stripped all catalogs. I can confirm that the 1.2.1-3-g9... fixes the issue on my environment, too.

**Comment by arubdesu** [comment] 2015-08-10 13:51
Yup, that did the trick. The screencast also showed that I didn't have checkboxes for catalogs in the manifest Properties... view before, either. Much betterer, thanks! 
I guess you want to leave this open until you do a new release?

**Comment by hjuutilainen** [comment] 2015-08-10 14:29
Thanks everybody. Let's keep this open until the fix is released, I think later today.

**Comment by hjuutilainen** [comment] 2015-08-10 17:53
Fix is included in 1.2.2 release. Closing...

**Closed by hjuutilainen** 2015-08-10 17:53 UTC
Labels: bug
